### ISSUE TITLE
can i host a html and javascript site?

### ISSUE THREAD

**Issue by Driesboy** [BoxOfDevs/Online#1]

**Comment by Ad5001** [comment]
Yes. Put the .js and the .html in your domain folder and it will work :)

**Comment by Ad5001** [comment]
Yes. Put the .js and the .html in your domain folder and it will work :)

**Comment by Ad5001** [comment]
Yes. Put the .js and the .html in your domain folder and it will work :)

**Comment by Driesboy** [comment]
k nothing others?

**Comment by Ad5001** [comment]
You can use PHP.

**Comment by Driesboy** [comment]
and how to use this ? https://github.com/Cryptkeeper/Minetrack

**Comment by Ad5001** [comment]
This is using Node.JS which don't uses online but is an app.

**Comment by Driesboy** [comment]
k
